name: parapred-pytorch-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/setup-python
      # this checks out the code
      - name: Code checkout
        uses: actions/checkout@v2

      # actually get Python into the ubuntu-20.04 container
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # https://docs.github.com/en/actions/guides/building-and-testing-python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make install

      - name: Integration tests for Parapred
        run: python -m unittest parapred/tests/test_parapred.py